config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :packages do
    resources :package_likes, only: :create do
      collection do
        get :like
        get :dislike
      end
    end
    member do
      get :download
      get :download_rap
    end
    collection do
      get :under_approval
      get :database
      post :download_database
    end
  end

  get :faq, to: 'home#faq'
  get :help_or_thank, to: 'home#help_or_thank'

  root to: 'home#index'
end

app/models/package_like.rb
class PackageLike < ApplicationRecord
  belongs_to :package
  belongs_to :user

  enum impact: { positive: 1, negative: 2 }, _prefix: true

  validates :impact, presence: true
  validates :reason, presence: true, if: -> { impact_negative? }
  validates :package, uniqueness: { scope: %i[package_id user_id] }
end

app/controllers/package_likes_controller.rb
class PackageLikesController < ApplicationController
  before_action :set_package
  before_action { authorize PackageLike }
  before_action { @norobot = true }

  def like
    handle_current_case!('positive')
  end

  def dislike
    handle_current_case!('negative')
  end

  def create
    @package_like = PackageLike.find_or_initialize_by(user: current_user, package: @package)

    if @package_like.persisted? && @package_like.impact == package_like_params[:impact]
      @package_like.destroy!
    else
      return render current_view unless @package_like.update(package_like_params)
    end

    redirect_to package_path(@package)
  end

  private

  def current_view
    package_like_params[:impact] == 'positive' ? :like : :dislike
  end

  def handle_current_case!(impact)
    current = PackageLike.find_or_initialize_by(user: current_user, package: @package)

    return if current.blank? || current.impact != impact

    current.destroy!

    redirect_to package_path(@package)
  end

  def set_package
    @package = Package.find(params[:package_id])
  end

  def package_like_params
    params.require(:package_like).permit(:impact, :reason)
  end
end

app/views/package_likes/dislike.html.haml
%h1.m-0= @package.title
= link_to package_path(@package) do
  %i.fas.fa-arrow-left
  = t('helpers.links.back')

%p.mt-4= t('.feedback_negative').html_safe

.card
  .card-header= t '.please_read'
  .card-body
    %p= t '.please_only_dislike_if'
    %p.font-weight-bold= t '.bad_reasons'
    %ul
      %li= t '.bad_reason_1'
      %li= t '.bad_reason_2'
    %p.font-weight-bold= t '.good_reasons'
    %ul
      %li= t '.good_reason_1'
      %li= t '.good_reason_2'
      %li= t '.good_reason_3'

    = simple_form_for @package_like || PackageLike.new, url: package_package_likes_path(@package), method: :post do |f|
      = f.input :impact, as: :hidden, input_html: { value: 'negative' }
      = f.input :reason
      = f.submit t('.i_swear'), class: 'btn btn-danger'
      = link_to t('.nevermind'), package_path(@package), class: 'btn btn-success'

app/views/package_likes/like.html.haml
%h1.m-0= @package.title
= link_to package_path(@package) do
  %i.fas.fa-arrow-left
  = t('helpers.links.back')

%p.mt-4= t('.feedback_positive').html_safe

.card
  .card-header= t '.please_read'
  .card-body
    %p= t '.please_only_like_if'
    %p.font-weight-bold= t '.bad_reasons'
    %ul
      %li= t '.bad_reason_1'
      %li= t '.bad_reason_2'
    %p.font-weight-bold= t '.good_reasons'
    %ul
      %li= t '.good_reason_1'

    = simple_form_for PackageLike.new, url: package_package_likes_path(@package), method: :post do |f|
      = f.input :impact, as: :hidden, input_html: { value: 'positive' }
      = f.submit t('.i_swear'), class: 'btn btn-success'
      = link_to t('.nevermind'), package_path(@package), class: 'btn btn-danger'